const CHAT_KEY="brightace_chat_session_v5";
const DEFAULT_API="https://script.google.com/macros/s/AKfycbz3yb5GmCDcyr1epRauGmPVyPFUcmzGy5s3X4Gs74a5J08kFzHHWKC05MX2hHW1UnWH/exec";
const CHAT_API_URL=window.BRIGHTACE_CHAT_API_URL||DEFAULT_API;
const POLL_MS=3000, MAX_FILE_MB=10;

function getRequestedContext(){try{const p=new URLSearchParams(window.location.search);return{service:(p.get("subject")||p.get("service")||"").trim(),resource:(p.get("resource")||"").trim(),help:(p.get("help")||"").trim()}}catch(e){return{service:"",resource:"",help:""}}}
function buildProfessionalRequest(service,resource,help){let s="Hello BrightAce Academy, I would like academic support";if(service)s+=" with "+service;if(resource)s+=(service?".":"")+" I am requesting help with the resource: "+resource;if(help)s+="\n\nHelp requested: "+help;s+=".\n\nPlease let me know the details you need from me. I can provide the specific questions, assignment instructions or requirements, relevant files/materials, and my preferred deadline. I would also like to discuss the appropriate support and next steps.";return s}
function prefillServiceRequest(){const c=getRequestedContext(),field=document.getElementById("taskDescription");if(!field||field.value.trim()||(!c.service&&!c.resource&&!c.help))return;field.value=buildProfessionalRequest(c.service,c.resource,c.help);const heading=document.querySelector("#chatStart h3"),helper=document.querySelector("#chatStart .chat-helper");if(heading)heading.textContent=c.resource?`Request help with ${c.resource}`:`Request help with ${c.service}`;if(helper)helper.textContent=c.resource?`Your request has been started for ${c.resource}. Please review the description and add any specific details before sending your request.`:`Your request has been started for ${c.service}. Please review the description and add any specific details before sending your request.`}

const startBox=document.getElementById("chatStart"),verificationArea=document.getElementById("verificationArea"),chatArea=document.getElementById("chatArea"),chatBody=document.getElementById("chatBody"),chatNotice=document.getElementById("chatNotice"),verificationNotice=document.getElementById("verificationNotice"),fileInput=document.getElementById("fileInput"),attachmentPreview=document.getElementById("attachmentPreview"),messageInput=document.getElementById("messageInput"),messageForm=document.getElementById("messageForm");
function safeParse(value,fallback=null){try{return JSON.parse(value)}catch(e){return fallback}}
let session=safeParse(localStorage.getItem(CHAT_KEY)||"null",null);
let selectedFiles=[],pollTimer=null,lastMessageSignature="";
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function apiReady(){return /^https:\/\/script\.google\.com\/macros\/s\/.+\/exec/.test(CHAT_API_URL)}
function setNotice(text,type="info"){if(!chatNotice)return;chatNotice.textContent=text;chatNotice.className="chat-notice "+type;chatNotice.hidden=!text}
function setVerificationNotice(text,type="info"){if(!verificationNotice)return;verificationNotice.textContent=text;verificationNotice.className="chat-notice "+type;verificationNotice.hidden=!text}
function fmtTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}
const WELCOME_MESSAGE="👋 Welcome to BrightAce Academy! I'm here to help you with your academic questions, assignments, and study needs. How can I help you today?";
function renderAttachment(a){if(!a)return"";const list=Array.isArray(a)?a:[a];return list.map(item=>{const name=esc(item.name||"Attachment"),url=item.viewUrl||item.url||"#",type=String(item.mimeType||"");if(type.startsWith("image/")&&url!=="#")return `<a class="msg-image-link" href="${esc(url)}" target="_blank" rel="noopener"><img class="msg-image" src="${esc(url)}" alt="${name}"></a><div class="msg-file"><span>📎 ${name}</span><a href="${esc(url)}" target="_blank" rel="noopener">View / Download</a></div>`;return `<div class="msg-file"><span>📎 ${name}</span>${url!=="#"?`<a href="${esc(url)}" target="_blank" rel="noopener">View / Download</a>`:""}</div>`}).join("")}
function addMessage(m){const d=document.createElement("div"),sender=m.sender==="student"?"student":"tutor";d.className="msg "+sender;d.dataset.messageId=m.id||"";d.innerHTML=`<div>${esc(m.text||"").replace(/\n/g,"<br>")}</div>${renderAttachment(m.attachment)}<small>${fmtTime(m.timestamp||new Date())}</small>`;chatBody.appendChild(d)}
function renderMessages(messages){const sig=messages.map(m=>`${m.id||""}:${m.status||""}:${m.timestamp||""}:${JSON.stringify(m.attachment||null)}`).join("|");if(sig===lastMessageSignature&&chatBody.children.length)return;const nearBottom=chatBody.scrollHeight-chatBody.scrollTop-chatBody.clientHeight<70;const oldTop=chatBody.scrollTop;lastMessageSignature=sig;chatBody.innerHTML="";addMessage({id:"brightace-welcome",sender:"tutor",text:WELCOME_MESSAGE,timestamp:session?.started||new Date()});messages.forEach(addMessage);if(nearBottom||!messages.length)chatBody.scrollTop=chatBody.scrollHeight;else chatBody.scrollTop=Math.min(oldTop,Math.max(0,chatBody.scrollHeight-chatBody.clientHeight))}
function openChat(){if(!startBox||!chatArea||!session?.verified)return;startBox.style.display="none";if(verificationArea)verificationArea.style.display="none";chatArea.style.display="block";document.getElementById("studentDisplay").textContent=session?.name||"Student";if(apiReady()){setNotice("Connected to BrightAce live chat.","success");syncMessages();clearInterval(pollTimer);pollTimer=setInterval(syncMessages,POLL_MS)}else{setNotice("Live chat requires the BrightAce server connection.","warning");renderMessages(session?.localMessages||[])}}
function showVerification(){if(startBox)startBox.style.display="none";if(chatArea)chatArea.style.display="none";if(verificationArea)verificationArea.style.display="block";setNotice("Verification required before live chat can begin.","info");document.getElementById("verificationCode")?.focus()}
async function post(action,payload={}){const body=new URLSearchParams();body.set("payload",JSON.stringify({action,...payload}));const r=await fetch(CHAT_API_URL,{method:"POST",body});const raw=await r.text();const d=safeParse(raw,null);if(!d)throw new Error("The BrightAce server returned an invalid response. Please try again.");if(!d.ok)throw new Error(d.error||"Server error");return d}
async function startRemoteChat(){return post("startChat",{id:session.id,name:session.name,phone:session.phone,taskDescription:session.taskDescription,studentBudget:session.studentBudget,currency:session.currency,deadline:session.deadline,consent:true})}
async function verifyRemoteChat(code){return post("verifyChat",{conversationId:session.id,code:String(code||"").trim()})}
async function resendRemoteCode(){return post("resendVerification",{conversationId:session.id})}
async function syncMessages(){if(!apiReady()||!session?.id||!session?.verified)return;try{const r=await fetch(`${CHAT_API_URL}?action=messages&sessionId=${encodeURIComponent(session.id)}`,{cache:"no-store"}),d=await r.json();if(d.ok){renderMessages(d.messages||[]);setNotice("Connected to BrightAce live chat.","success")}}catch(e){setNotice("Live connection is temporarily unavailable. Retrying…","warning")}}
function renderSelectedFiles(){if(!attachmentPreview)return;if(!selectedFiles.length){attachmentPreview.hidden=true;attachmentPreview.innerHTML="";return}attachmentPreview.hidden=false;attachmentPreview.innerHTML=selectedFiles.map((f,i)=>`<span class="attachment-chip">📎 ${esc(f.name)} · ${(f.size/1024/1024).toFixed(1)} MB <button type="button" data-remove-file="${i}" aria-label="Remove ${esc(f.name)}">×</button></span>`).join("");attachmentPreview.querySelectorAll("[data-remove-file]").forEach(b=>b.addEventListener("click",()=>{selectedFiles.splice(Number(b.dataset.removeFile),1);renderSelectedFiles()}))}
function addSelectedFiles(fileList){const incoming=Array.from(fileList||[]);for(const f of incoming){if(f.size>MAX_FILE_MB*1024*1024){setNotice(`Please choose files smaller than ${MAX_FILE_MB} MB each.` ,"error");continue}if(selectedFiles.some(x=>x.name===f.name&&x.size===f.size&&x.lastModified===f.lastModified))continue;if(selectedFiles.length>=5){setNotice("You can attach up to 5 files per message.","error");break}selectedFiles.push(f)}renderSelectedFiles()}
fileInput?.addEventListener("change",()=>{addSelectedFiles(fileInput.files);fileInput.value=""});
const EMOJIS=["😀","😃","😄","😁","😆","😂","🤣","😊","😇","🙂","😉","😍","🥰","😎","🤓","🤩","🥳","😢","😭","😮","😲","🤔","🙄","😴","🤗","👍","👎","👏","🙏","💪","❤️","💯","🔥","✨","🎉","🎓","📚","📖","✏️","📝","🧮","🔬","💡","📊","📈","💻","✅","❌","❓","❗","⭐","🚀","💬"];
function createEmojiPicker(){if(!messageForm)return null;let p=document.getElementById("emojiPicker");if(p)return p;p=document.createElement("div");p.id="emojiPicker";p.className="emoji-picker";EMOJIS.forEach(e=>{const b=document.createElement("button");b.type="button";b.className="emoji-choice";b.textContent=e;b.addEventListener("click",()=>{const s=messageInput.selectionStart??messageInput.value.length,en=messageInput.selectionEnd??messageInput.value.length;messageInput.value=messageInput.value.slice(0,s)+e+messageInput.value.slice(en);messageInput.focus();messageInput.setSelectionRange(s+e.length,s+e.length);p.classList.remove("open")});p.appendChild(b)});messageForm.appendChild(p);return p}
document.getElementById("emojiBtn")?.addEventListener("click",e=>{e.preventDefault();createEmojiPicker()?.classList.toggle("open")});
document.addEventListener("click",e=>{const p=document.getElementById("emojiPicker"),b=document.getElementById("emojiBtn");if(p?.classList.contains("open")&&!p.contains(e.target)&&e.target!==b)p.classList.remove("open")});
document.getElementById("photoBtn")?.addEventListener("click",()=>{fileInput.accept="image/*";fileInput.click()});
document.getElementById("attachBtn")?.addEventListener("click",()=>{fileInput.accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv,.zip";fileInput.click()});
function saveStartDraft(){try{localStorage.setItem("brightace_start_draft_v2",JSON.stringify({name:document.getElementById("studentName")?.value||"",phone:document.getElementById("studentPhone")?.value||"",taskDescription:document.getElementById("taskDescription")?.value||"",studentBudget:document.getElementById("studentBudget")?.value||"",currency:document.getElementById("studentCurrency")?.value||"KES",deadline:document.getElementById("studentDeadline")?.value||"",consent:!!document.getElementById("consent")?.checked}))}catch(e){}}
function restoreStartDraft(){try{const d=safeParse(localStorage.getItem("brightace_start_draft_v2")||localStorage.getItem("brightace_start_draft_v1")||"null",null);if(!d)return;["studentName","studentPhone","taskDescription","studentBudget","studentDeadline"].forEach(k=>{if(d[k]!==undefined&&document.getElementById(k))document.getElementById(k).value=d[k]});if(d.currency&&document.getElementById("studentCurrency"))document.getElementById("studentCurrency").value=d.currency;if(document.getElementById("consent"))document.getElementById("consent").checked=!!d.consent}catch(e){}}
["studentName","studentPhone","taskDescription","studentBudget","studentCurrency","studentDeadline","consent"].forEach(id=>document.getElementById(id)?.addEventListener("input",saveStartDraft));
restoreStartDraft();

document.getElementById("startForm")?.addEventListener("submit",async e=>{e.preventDefault();const btn=document.getElementById("startChatBtn"),name=document.getElementById("studentName").value.trim(),phone=document.getElementById("studentPhone").value.trim(),task=document.getElementById("taskDescription").value.trim(),budget=Number(document.getElementById("studentBudget").value),currency=document.getElementById("studentCurrency").value,deadline=document.getElementById("studentDeadline").value.trim();if(!name||!phone||!task||!(budget>0))return;if(!apiReady()){setNotice("The BrightAce verification service is not connected. Please try again when the live service is available.","error");return}const oldText=btn?.textContent;if(btn){btn.disabled=true;btn.textContent="SENDING REQUEST…"}session={id:"CHAT-"+Date.now().toString(36).toUpperCase(),name,phone,taskDescription:task,studentBudget:budget,currency,deadline,started:new Date().toISOString(),verified:false};localStorage.setItem(CHAT_KEY,JSON.stringify(session));try{const data=await startRemoteChat();if(!data?.ok||!data.conversationId)throw new Error(data?.error||"The server did not create the verification request.");session.id=data.conversationId;session.verified=false;localStorage.setItem(CHAT_KEY,JSON.stringify(session));localStorage.removeItem("brightace_start_draft_v2");showVerification();setVerificationNotice(data.message||"A 6-digit verification code has been sent to your WhatsApp number.","success")}catch(err){if(startBox)startBox.style.display="block";if(verificationArea)verificationArea.style.display="none";setNotice("Request was not submitted: "+(err?.message||"Please try again."),"error")}finally{if(btn){btn.disabled=false;btn.textContent=oldText}}});

document.getElementById("verificationForm")?.addEventListener("submit",async e=>{e.preventDefault();const code=document.getElementById("verificationCode")?.value.trim()||"",btn=document.getElementById("verifyBtn");if(!/^\d{6}$/.test(code)){setVerificationNotice("Enter the 6-digit code sent to your WhatsApp number.","error");return}btn.disabled=true;btn.textContent="VERIFYING…";try{const d=await verifyRemoteChat(code);session.verified=true;session.localMessages=[];localStorage.setItem(CHAT_KEY,JSON.stringify(session));openChat();setNotice(d.message||"WhatsApp verified. Your BrightAce live chat is now connected.","success");syncMessages().catch(()=>{})}catch(err){setVerificationNotice(err?.message||"The code could not be verified. Please try again.","error")}finally{btn.disabled=false;btn.textContent="VERIFY & CONNECT"}});

document.getElementById("resendBtn")?.addEventListener("click",async()=>{if(!session?.id)return;const btn=document.getElementById("resendBtn");btn.disabled=true;btn.textContent="SENDING…";let exhausted=false;try{const d=await resendRemoteCode();setVerificationNotice((d.message||"A new 6-digit verification code has been sent to your WhatsApp number.")+(typeof d.remainingResends==="number"?" "+d.remainingResends+" new request"+(d.remainingResends===1?"":"s")+" remaining.":""),"success");if(typeof d.remainingResends==="number"&&d.remainingResends<=0){exhausted=true;btn.textContent="NO MORE CODES"}}catch(err){setVerificationNotice(err?.message||"A new code could not be sent.","error")}finally{if(!exhausted){btn.disabled=false;btn.textContent="REQUEST A NEW CODE"}}});

messageForm?.addEventListener("submit",async e=>{e.preventDefault();if(!session?.id||!session?.verified){setNotice("Please verify your WhatsApp number before starting the chat.","error");return}const text=messageInput.value.trim();if(!text&&!selectedFiles.length)return;const sendBtn=messageForm.querySelector(".send-btn");if(sendBtn){sendBtn.disabled=true;sendBtn.textContent="…"}try{let attachments=[];for(const file of selectedFiles){const reader=new FileReader();const dataUrl=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("Could not read an attachment."));reader.readAsDataURL(file)});attachments.push({name:file.name,mimeType:file.type||"application/octet-stream",size:file.size,dataUrl})}if(apiReady()){if(sendBtn&&attachments.length)sendBtn.textContent="UPLOADING ATTACHMENTS…"; const data=await post("sendMessage",{sessionId:session.id,text,attachments});if(!data?.ok)throw new Error(data?.error||"Message was not accepted by the server.");messageInput.value="";selectedFiles=[];renderSelectedFiles();if(fileInput)fileInput.value="";syncMessages().catch(()=>{});if(sendBtn)sendBtn.textContent="SENT ✓"; setNotice(data.whatsapp?.sentTo?"Message sent.":"Message submitted.","success")}else{throw new Error("Live chat service is unavailable.")}}catch(err){setNotice((err&&err.message)||"Message could not be sent. Please try again.","error")}finally{if(sendBtn){sendBtn.disabled=false;sendBtn.textContent="➤"}}});

document.getElementById("refundToggle")?.addEventListener("click",()=>{const panel=document.getElementById("refundPanel"),btn=document.getElementById("refundToggle");if(!panel||!btn)return;const open=panel.hidden;panel.hidden=!open;btn.textContent=open?"✕ CLOSE REFUND REQUEST":"💳 REQUEST A REFUND";if(open)panel.scrollIntoView({behavior:"smooth",block:"nearest"})});
document.getElementById("refundCancel")?.addEventListener("click",()=>{const panel=document.getElementById("refundPanel"),btn=document.getElementById("refundToggle");if(panel)panel.hidden=true;if(btn)btn.textContent="💳 REQUEST A REFUND"});
document.getElementById("refundForm")?.addEventListener("submit",async e=>{e.preventDefault();if(!session?.id||!session?.verified){const n=document.getElementById("refundNotice");if(n){n.textContent="Please verify and start your BrightAce chat before submitting a refund request.";n.className="chat-notice error";n.hidden=false}return}const btn=e.submitter,notice=document.getElementById("refundNotice"),setR=(t,type="info")=>{if(notice){notice.textContent=t;notice.className="chat-notice "+type;notice.hidden=!t}},reason=document.getElementById("refundReason")?.value.trim(),amount=Number(document.getElementById("refundAmount")?.value||0),currency=document.getElementById("refundCurrency")?.value||"KES",paymentRequestId=document.getElementById("refundPaymentRequestId")?.value.trim()||"";if(!paymentRequestId){setR("Please provide your payment/refund code.","error");return}if(!reason){setR("Please provide a reason for your refund request.","error");return}btn.disabled=true;try{await post("submitRefundRequest",{conversationId:session.id,paymentRequestId,amount,currency,reason,studentEmail:""});document.getElementById("refundReason").value="";document.getElementById("refundAmount").value="";setR("Refund request submitted. BrightAce Admin will review it and contact you through the chat/WhatsApp.","success");await syncMessages()}catch(err){setR(err?.message||"Refund request could not be submitted.","error")}finally{btn.disabled=false}});
document.getElementById("newChatBtn")?.addEventListener("click",()=>{clearInterval(pollTimer);localStorage.removeItem(CHAT_KEY);localStorage.removeItem("brightace_start_draft_v2");localStorage.removeItem("brightace_start_draft_v1");localStorage.removeItem("brightace_chat_session_v4");location.reload()});

if(session?.verified)openChat();else if(session?.id&&session?.name&&session?.phone){showVerification();setVerificationNotice("Enter the 6-digit code sent to your WhatsApp number. If it has expired, request a new code.","info")}

prefillServiceRequest();
