/* BrightAce V58 — Resource Commerce + Secure Access.
   Resource catalog remains Google Drive-backed and USD-priced.
   This module adds thumbnails, provider-neutral payment calls, purchases/access,
   duplicate-purchase protection, refund/reconciliation state, and audit records.
*/

function getConfig_(){
  const p=PropertiesService.getScriptProperties();
  return {spreadsheetId:String(p.getProperty(CONFIG.spreadsheetIdKey)||"").trim(),recoveryMaxRowsPerSheet:Number(p.getProperty("RECOVERY_MAX_ROWS_PER_SHEET")||50000),resourceDriveFolderId:String(p.getProperty("RESOURCE_DRIVE_FOLDER_ID")||"").trim()};
}

function baResourceHeaders_(){return ["resourceId","title","category","description","priceUSD","driveFileId","fileName","thumbnailFileId","thumbnailFileName","published","accessLevel","sortOrder","createdAt","updatedAt","accessDurationDays"]}
function baPurchaseHeaders_(){return ["purchaseId","resourceId","resourceTitle","customerName","customerEmail","customerPhone","amountUSD","currency","status","provider","providerReference","authorizationUrl","createdAt","paidAt","refundedAt","refundAmountUSD","refundReference","accessRevokedAt"]}
function baAccessHeaders_(){return ["accessId","purchaseId","resourceId","customerEmail","customerPhone","accessStatus","firstGrantedAt","lastAccessAt","accessCount","lastDownloadAt","downloadCount","lastUserAgent","expiresAt"]}
function baResourceSheet_(){return ensureColumns_(getSheet_("RESOURCES",baResourceHeaders_()),baResourceHeaders_())}
function baPurchaseSheet_(){return ensureColumns_(getSheet_("RESOURCE_PURCHASES",baPurchaseHeaders_()),baPurchaseHeaders_())}
function baAccessSheet_(){return ensureColumns_(getSheet_("RESOURCE_ACCESS",baAccessHeaders_()),baAccessHeaders_())}

function baResourceRow_(r,row){return {row:row,resourceId:String(r[0]||""),title:String(r[1]||""),category:String(r[2]||""),description:String(r[3]||""),priceUSD:Number(r[4]||0),driveFileId:String(r[5]||""),fileName:String(r[6]||""),thumbnailFileId:String(r[7]||""),thumbnailFileName:String(r[8]||""),published:String(r[9]||"NO").toUpperCase()==="YES",accessLevel:String(r[10]||"PUBLIC").toUpperCase(),sortOrder:Number(r[11]||0),createdAt:r[12]||"",updatedAt:r[13]||"",accessDurationDays:Number(r[14]||0)||0}}
function baFindResource_(id){const target=String(id||"").trim();if(!target)return null;const key="BA_RESOURCE_"+target,hit=baCacheGetJson_(key);if(hit&&hit.resourceId)return hit;const sh=baResourceSheet_(),last=sh.getLastRow();if(last<2)return null;const cell=sh.getRange(2,1,last-1,1).createTextFinder(target).matchEntireCell(true).useRegularExpression(false).findNext();if(!cell)return null;const out=baResourceRow_(sh.getRange(cell.getRow(),1,1,sh.getLastColumn()).getValues()[0],cell.getRow());baCachePutJson_(key,out,120);return out}
function baResourceThumbnailUrl_(r){if(!r||!r.thumbnailFileId)return "";return "https://drive.google.com/thumbnail?id="+encodeURIComponent(r.thumbnailFileId)+"&sz=w480"}
function baResourcePublic_(r){return {resourceId:r.resourceId,title:r.title,category:r.category,description:r.description,priceUSD:Number(r.priceUSD||0),currency:"USD",fileName:r.fileName,thumbnailUrl:baResourceThumbnailUrl_(r),published:!!r.published,accessLevel:r.accessLevel,sortOrder:r.sortOrder,accessDurationDays:Number(r.accessDurationDays||0)}}
function baResourceList_(publishedOnly){return baCachedResourceList_(!!publishedOnly)}
function baValidateResource_(d){
  const title=String(d.title||"").trim(),category=String(d.category||"").trim(),description=String(d.description||"").trim(),price=Number(d.priceUSD),fileId=String(d.driveFileId||"").trim(),thumbId=String(d.thumbnailFileId||"").trim();
  if(title.length<2||title.length>160)throw new Error("Resource title must be 2–160 characters.");if(category.length>80)throw new Error("Resource category is too long.");if(description.length>2000)throw new Error("Resource description is too long.");if(!isFinite(price)||price<=0||price>100000)throw new Error("Resource price must be greater than $0 and no more than $100,000.");
  if(!/^[A-Za-z0-9_-]{10,}$/.test(fileId))throw new Error("Enter a valid Google Drive file ID.");
  const accessDurationDays=Math.floor(Number(d.accessDurationDays||0));if(!isFinite(accessDurationDays)||accessDurationDays<0||accessDurationDays>3650)throw new Error("Access duration must be 0 (unlimited) or between 1 and 3650 days.");
  let f;try{f=DriveApp.getFileById(fileId)}catch(e){throw new Error("Google Drive resource file could not be opened with that file ID.")}
  if(thumbId){let tf;try{tf=DriveApp.getFileById(thumbId)}catch(e){throw new Error("Google Drive thumbnail file could not be opened.")}if(String(tf.getMimeType()||"").indexOf("image/")!==0)throw new Error("Thumbnail file must be an image (JPG, PNG, WEBP, GIF, etc.).")}
  return {title:title,category:category,description:description,priceUSD:Math.round(price*100)/100,driveFileId:fileId,fileName:f.getName(),thumbnailFileId:thumbId,thumbnailFileName:thumbId?DriveApp.getFileById(thumbId).getName():"",published:String(d.published||"NO").toUpperCase()==="YES",accessLevel:String(d.accessLevel||"PUBLIC").toUpperCase()==="STUDENT"?"STUDENT":"PUBLIC",sortOrder:Number(d.sortOrder||0)||0,accessDurationDays:accessDurationDays}
}
function adminListResources_(token){requireSuperAdmin_(token);return json_({ok:true,resources:baResourceList_(false).map(baResourcePublic_),generatedAt:new Date().toISOString()})}
function publicResourceCatalog_(){return json_({ok:true,resources:baResourceList_(true).map(baResourcePublic_),generatedAt:new Date().toISOString()})}
function adminSaveResource_(d){
  requireSuperAdmin_(d.adminToken);const x=baValidateResource_(d),now=new Date(),existing=String(d.resourceId||"").trim(),sh=baResourceSheet_(),m=headerMap_(sh);
  if(existing){const old=baFindResource_(existing);if(!old)throw new Error("Resource not found.");const vals={title:x.title,category:x.category,description:x.description,priceUSD:x.priceUSD,driveFileId:x.driveFileId,fileName:x.fileName,thumbnailFileId:x.thumbnailFileId,thumbnailFileName:x.thumbnailFileName,published:x.published?"YES":"NO",accessLevel:x.accessLevel,sortOrder:x.sortOrder,updatedAt:now,accessDurationDays:x.accessDurationDays};Object.keys(vals).forEach(k=>{if(m[k])sh.getRange(old.row,m[k]).setValue(vals[k])});baCacheRemove_("BA_RESOURCE_"+existing);baResourceInvalidateIndexes_();auditAdmin_(d.adminToken,"RESOURCE_UPDATED",existing);return json_({ok:true,resource:baResourcePublic_(baFindResource_(existing)||Object.assign({},old,vals))})}
  const id="BA-RES-"+Utilities.getUuid().replace(/-/g,"").slice(0,16).toUpperCase(),row=sh.getLastRow()+1,vals=[id,x.title,x.category,x.description,x.priceUSD,x.driveFileId,x.fileName,x.thumbnailFileId,x.thumbnailFileName,x.published?"YES":"NO",x.accessLevel,x.sortOrder,now,now,x.accessDurationDays];sh.getRange(row,1,1,vals.length).setValues([vals]);baResourceInvalidateIndexes_();auditAdmin_(d.adminToken,"RESOURCE_CREATED",id);return json_({ok:true,resource:baResourcePublic_(baResourceRow_(vals,row))})
}
function adminDeleteResource_(d){requireSuperAdmin_(d.adminToken);const r=baFindResource_(d.resourceId);if(!r)throw new Error("Resource not found.");const purchases=baPurchaseSheet_(),m=headerMap_(purchases),last=purchases.getLastRow();if(last>1&&m.resourceId){const vals=purchases.getRange(2,m.resourceId,last-1,1).getValues();for(let i=0;i<vals.length;i++)if(String(vals[i][0])===r.resourceId)throw new Error("This resource has purchase records and cannot be deleted. Unpublish it instead.")}baResourceSheet_().deleteRow(r.row);baCacheRemove_("BA_RESOURCE_"+r.resourceId);baResourceInvalidateIndexes_();auditAdmin_(d.adminToken,"RESOURCE_DELETED",r.resourceId);return json_({ok:true,deleted:r.resourceId})}

/* ===================== PAYMENT PROVIDER ABSTRACTION ===================== */
function baResourcePaymentProvider_(){return String(PropertiesService.getScriptProperties().getProperty("BRIGHTACE_RESOURCE_PAYMENT_PROVIDER")||"PAYSTACK").trim().toUpperCase()||"PAYSTACK"}
function baPaymentProviderInitialize_(args){const provider=baResourcePaymentProvider_();if(provider!=="PAYSTACK")throw new Error("Resource payment provider '"+provider+"' is not configured yet. Add its integration before switching providers.");return baPaystackInitializeResourcePayment_(args)}
function baPaymentProviderVerify_(reference){const provider=baResourcePaymentProvider_();if(provider!=="PAYSTACK")throw new Error("Resource payment provider '"+provider+"' is not configured yet.");return baPaystackVerifyResourcePayment_(reference)}
function baPaymentProviderRefund_(reference,amountUSD){const provider=baResourcePaymentProvider_();if(provider!=="PAYSTACK")throw new Error("Resource payment provider '"+provider+"' is not configured yet.");return paystackRefund_(reference,amountUSD,"USD")}
function baPaystackInitializeResourcePayment_(args){
  const secret=String(PropertiesService.getScriptProperties().getProperty(CONFIG.paystackSecretKey)||"").trim();if(!secret)throw new Error("Current resource payment provider is not configured. Add PAYSTACK_SECRET_KEY in Apps Script Script Properties.");if(!/^sk_(test|live)_/.test(secret))throw new Error("Invalid Paystack secret-key format.");
  const payload={email:args.email,amount:String(toPaystackMinorUnit_(args.amountUSD,"USD")),currency:"USD",reference:args.reference,callback_url:args.callbackUrl,metadata:JSON.stringify(args.metadata||{})};
  const response=UrlFetchApp.fetch("https://api.paystack.co/transaction/initialize",{method:"post",contentType:"application/json",headers:{Authorization:"Bearer "+secret},payload:JSON.stringify(payload),muteHttpExceptions:true}),data=JSON.parse(response.getContentText()||"{}");
  if(response.getResponseCode()>=300||!data.status||!data.data||!data.data.authorization_url)throw new Error("Payment initialization failed: "+String(data.message||response.getContentText()||"Unknown error"));
  return {provider:"PAYSTACK",authorizationUrl:data.data.authorization_url,reference:String(data.data.reference||args.reference),raw:data.data}
}
function baPaystackVerifyResourcePayment_(reference){
  const secret=String(PropertiesService.getScriptProperties().getProperty(CONFIG.paystackSecretKey)||"").trim();if(!secret)throw new Error("Current resource payment provider is not configured.");
  const response=UrlFetchApp.fetch("https://api.paystack.co/transaction/verify/"+encodeURIComponent(reference),{headers:{Authorization:"Bearer "+secret},muteHttpExceptions:true}),data=JSON.parse(response.getContentText()||"{}");
  if(response.getResponseCode()>=300||!data.status||!data.data)throw new Error(String(data.message||"Unable to verify payment."));return data.data
}

/* ===================== PURCHASES / ACCESS ===================== */
function baPurchaseFromRow_(v,row,m){return {row:row,purchaseId:String(v[m.purchaseId-1]||""),resourceId:String(v[m.resourceId-1]||""),resourceTitle:String(v[m.resourceTitle-1]||""),customerName:String(v[m.customerName-1]||""),customerEmail:String(v[m.customerEmail-1]||"").toLowerCase(),customerPhone:String(v[m.customerPhone-1]||""),amountUSD:Number(v[m.amountUSD-1]||0),currency:String(v[m.currency-1]||"USD").toUpperCase(),status:String(v[m.status-1]||"PENDING").toUpperCase(),provider:String(v[m.provider-1]||"PAYSTACK").toUpperCase(),reference:String(v[m.providerReference-1]||""),authorizationUrl:String(v[m.authorizationUrl-1]||""),createdAt:v[m.createdAt-1]||"",paidAt:v[m.paidAt-1]||"",refundedAt:v[m.refundedAt-1]||"",refundAmountUSD:Number(v[m.refundAmountUSD-1]||0),refundReference:String(v[m.refundReference-1]||""),accessRevokedAt:v[m.accessRevokedAt-1]||""}}
function baFindPurchaseByReference_(reference){const target=String(reference||"").trim();if(!target)return null;const sh=baPurchaseSheet_(),last=sh.getLastRow();if(last<2)return null;const m=headerMap_(sh),cell=sh.getRange(2,m.providerReference,last-1,1).createTextFinder(target).matchEntireCell(true).useRegularExpression(false).findNext();if(!cell)return null;return baPurchaseFromRow_(sh.getRange(cell.getRow(),1,1,sh.getLastColumn()).getValues()[0],cell.getRow(),m)}
function baFindPurchaseById_(purchaseId){const id=String(purchaseId||"").trim();if(!id)return null;const sh=baPurchaseSheet_(),row=baPurchaseIndex_()[id];if(!row)return null;const m=headerMap_(sh);return baPurchaseFromRow_(sh.getRange(row,1,1,sh.getLastColumn()).getValues()[0],row,m)}
function baPurchaseHasPaid_(resourceId,email,phone){const em=String(email||"").trim().toLowerCase(),ph=normalizePhone_(phone||"");const keys=baPaidKeySet_();return !!((em&&keys[String(resourceId)+"|e|"+em])||(ph&&keys[String(resourceId)+"|p|"+ph]))}
function baAccessExpiryForPurchase_(p,fromDate){const r=baFindResource_(p&&p.resourceId);const days=Number(r&&r.accessDurationDays||0);if(!(days>0))return "";const base=fromDate instanceof Date?new Date(fromDate.getTime()):new Date();return new Date(base.getTime()+days*86400000)}
function baEnsureAccess_(p){const sh=baAccessSheet_(),m=headerMap_(sh),last=sh.getLastRow(),rows=last>1?sh.getRange(2,1,last-1,sh.getLastColumn()).getValues():[];for(let i=0;i<rows.length;i++){if(String(rows[i][m.purchaseId-1]||"")===p.purchaseId)return {row:i+2,values:rows[i]}}const id="BA-ACC-"+Utilities.getUuid().replace(/-/g,"").slice(0,12).toUpperCase(),now=new Date(),expiry=baAccessExpiryForPurchase_(p,now),vals=[id,p.purchaseId,p.resourceId,p.customerEmail,p.customerPhone,"ACTIVE",now,now,0,"",0,"",expiry];sh.appendRow(vals);baResourceInvalidateIndexes_();return {row:sh.getLastRow(),values:vals}}

function baFindAccessByPurchaseId_(purchaseId){const id=String(purchaseId||"").trim();if(!id)return null;const sh=baAccessSheet_(),row=baAccessIndex_()[id];if(!row)return null;return {row:row,values:sh.getRange(row,1,1,sh.getLastColumn()).getValues()[0]};}
function baResourceAccessActive_(p){
  if(!p||p.status!=="PAID"||p.accessRevokedAt)return false;
  const a=baFindAccessByPurchaseId_(p.purchaseId);if(!a)return true;
  const m=headerMap_(baAccessSheet_()),status=String(a.values[m.accessStatus-1]||"ACTIVE").toUpperCase(),expires=m.expiresAt? a.values[m.expiresAt-1] : "";
  if(status!=="ACTIVE")return false;
  if(expires){const t=new Date(expires).getTime();if(isFinite(t)&&t<=Date.now())return false;}
  return true;
}

function baRecordAccess_(p,kind,userAgent){const a=baEnsureAccess_(p),sh=baAccessSheet_(),m=headerMap_(sh),now=new Date();setByHeader_(sh,a.row,"lastAccessAt",now);setByHeader_(sh,a.row,"accessCount",Number(getByHeader_(sh,a.row,"accessCount")||0)+1);if(kind==="DOWNLOAD"){setByHeader_(sh,a.row,"lastDownloadAt",now);setByHeader_(sh,a.row,"downloadCount",Number(getByHeader_(sh,a.row,"downloadCount")||0)+1)}if(userAgent)setByHeader_(sh,a.row,"lastUserAgent",String(userAgent).slice(0,300))}

function resourceInitializePayment_(d){
  const r=baFindResource_(d.resourceId);if(!r||!r.published)throw new Error("Resource is not available for purchase.");if(r.accessLevel!=="PUBLIC")throw new Error("This resource requires an authenticated BrightAce account and is not available through public checkout yet.");
  const name=String(d.customerName||"").trim(),email=String(d.customerEmail||"").trim().toLowerCase(),phone=normalizePhone_(d.customerPhone||"");if(name.length<2||name.length>120)throw new Error("Enter your name.");if(!/^\S+@\S+\.\S+$/.test(email))throw new Error("Enter a valid email address.");
  if(baPurchaseHasPaid_(r.resourceId,email,phone))throw new Error("This resource is already in your BrightAce purchases.");
  const sh=baPurchaseSheet_(),purchaseId="BA-RP-"+Utilities.getUuid().replace(/-/g,"").slice(0,18).toUpperCase(),reference=purchaseId+"-"+Utilities.getUuid().replace(/-/g,"").slice(0,10),callback=PropertiesService.getScriptProperties().getProperty(CONFIG.paymentCallbackUrlKey)||"https://kamaujames64-lgtm.github.io/brightace-academy/pages/resource-checkout.html";
  const result=baPaymentProviderInitialize_({email:email,amountUSD:r.priceUSD,reference:reference,callbackUrl:callback,metadata:{resourcePurchaseId:purchaseId,resourceId:r.resourceId,resourceTitle:r.title,customerName:name,customerEmail:email,customerPhone:phone}});
  sh.appendRow([purchaseId,r.resourceId,r.title,name,email,phone,r.priceUSD,"USD","PENDING",result.provider,result.reference,result.authorizationUrl,new Date(),"","",0,"",""]);baResourceInvalidateIndexes_();
  return json_({ok:true,purchaseId:purchaseId,resourceId:r.resourceId,authorizationUrl:result.authorizationUrl,reference:result.reference,amountUSD:r.priceUSD,currency:"USD",provider:result.provider})
}
function baVerifyAndRecordResourcePurchase_(reference){
  const p=baFindPurchaseByReference_(reference);if(!p)throw new Error("Resource purchase not found.");if(p.status==="PAID")return p;const tx=baPaymentProviderVerify_(reference);if(String(tx.status||"").toLowerCase()!=="success")return p;const r=baFindResource_(p.resourceId);if(!r)throw new Error("The purchased resource is no longer available.");if(Number(tx.amount)!==toPaystackMinorUnit_(p.amountUSD,"USD")||String(tx.currency||"").toUpperCase()!=="USD")throw new Error("Payment amount or currency did not match the resource price.");const sh=baPurchaseSheet_(),m=headerMap_(sh);setByHeader_(sh,p.row,"status","PAID");setByHeader_(sh,p.row,"paidAt",tx.paid_at||new Date());const updated=Object.assign({},p,{status:"PAID",paidAt:tx.paid_at||new Date()});baEnsureAccess_(updated);baResourceInvalidateIndexes_();return updated
}
function resourceVerifyPayment_(reference){const p=baVerifyAndRecordResourcePurchase_(reference),r=baFindResource_(p.resourceId);return json_({ok:true,status:p.status==="PAID"?"success":"pending",reference:p.reference,purchaseId:p.purchaseId,resourceId:p.resourceId,resourceTitle:p.resourceTitle,amountUSD:p.amountUSD,currency:"USD",thumbnailUrl:r?baResourceThumbnailUrl_(r):"",downloadUrl:baResourceAccessActive_(p)&&r&&r.driveFileId?DriveApp.getFileById(r.driveFileId).getUrl():"",paidAt:p.paidAt||"",provider:p.provider})}
function resourceDownloadInfo_(purchaseId,reference,userAgent){const p=reference?baFindPurchaseByReference_(reference):baFindPurchaseById_(purchaseId);if(!p||String(p.purchaseId)!==String(purchaseId||p.purchaseId))throw new Error("Purchase not found.");if(!baResourceAccessActive_(p))throw new Error("Resource access is not active.");const r=baFindResource_(p.resourceId);if(!r)throw new Error("Resource not found.");baRecordAccess_(p,"DOWNLOAD",userAgent||"");let url="";try{url=DriveApp.getFileById(r.driveFileId).getUrl()}catch(e){throw new Error("The Google Drive resource is unavailable.")}return json_({ok:true,resourceId:r.resourceId,title:r.title,thumbnailUrl:baResourceThumbnailUrl_(r),downloadUrl:url})}

function clientResourceCatalog_(d){
  const c=requireClientSession_(d.clientSessionToken,d.phone),phone=normalizePhone_(c.clientPhone||d.phone||""),email=String(c.clientEmail||c.email||"").trim().toLowerCase();
  const resources=baResourceList_(true),sh=baPurchaseSheet_(),m=headerMap_(sh),last=sh.getLastRow(),owned={};
  if(last>1){const vals=sh.getRange(2,1,last-1,sh.getLastColumn()).getValues();for(let i=0;i<vals.length;i++){const p=baPurchaseFromRow_(vals[i],i+2,m);if(!p.resourceId||!((email&&p.customerEmail===email)||(phone&&normalizePhone_(p.customerPhone)===phone)))continue;if(p.status==="PAID"&&!p.accessRevokedAt)owned[p.resourceId]={purchaseId:p.purchaseId,purchasedAt:p.paidAt,accessStatus:baResourceAccessActive_(p)?"ACTIVE":"EXPIRED",expiresAt:(function(){const a=baFindAccessByPurchaseId_(p.purchaseId),am=a?headerMap_(baAccessSheet_()):null;return a&&am&&am.expiresAt?a.values[am.expiresAt-1]:""})()};else if(!owned[p.resourceId]&&p.status==="REFUNDED")owned[p.resourceId]={purchaseId:p.purchaseId,purchasedAt:p.paidAt,accessStatus:"REVOKED",expiresAt:""};}}
  return json_({ok:true,resources:resources.map(function(r){const o=owned[r.resourceId]||null;return {resourceId:r.resourceId,title:r.title,category:r.category,description:r.description,priceUSD:r.priceUSD,currency:"USD",fileName:r.fileName,thumbnailUrl:baResourceThumbnailUrl_(r),published:r.published,accessLevel:r.accessLevel,sortOrder:r.sortOrder,purchased:!!(o&&o.accessStatus==="ACTIVE"),purchaseId:o?o.purchaseId:"",purchasedAt:o?o.purchasedAt:"",accessStatus:o?o.accessStatus:"NOT_PURCHASED",expiresAt:o?o.expiresAt:""};}),generatedAt:new Date().toISOString()});
}

function clientResourceLibrary_(d){
  const c=requireClientSession_(d.clientSessionToken,d.phone),phone=normalizePhone_(c.clientPhone||d.phone||""),email=String(c.clientEmail||c.email||"").trim().toLowerCase(),sh=baPurchaseSheet_(),m=headerMap_(sh),last=sh.getLastRow(),out=[];if(last>1){const vals=sh.getRange(2,1,last-1,sh.getLastColumn()).getValues();for(let i=0;i<vals.length;i++){const p=baPurchaseFromRow_(vals[i],i+2,m);if(p.status!=="PAID"||p.accessRevokedAt)continue;if(!((email&&p.customerEmail===email)||(phone&&normalizePhone_(p.customerPhone)===phone)))continue;const r=baFindResource_(p.resourceId);out.push({purchaseId:p.purchaseId,resourceId:p.resourceId,title:p.resourceTitle,category:r?r.category:"",description:r?r.description:"",priceUSD:p.amountUSD,currency:"USD",purchasedAt:p.paidAt,thumbnailUrl:r?baResourceThumbnailUrl_(r):"",fileName:r?r.fileName:"",accessStatus:"ACTIVE",expiresAt:(function(){const a=baFindAccessByPurchaseId_(p.purchaseId),am=a?headerMap_(baAccessSheet_()):null;return a&&am&&am.expiresAt?a.values[am.expiresAt-1]:""})()})}}
  out.sort((a,b)=>new Date(b.purchasedAt||0)-new Date(a.purchasedAt||0));return json_({ok:true,resources:out.slice(0,200),generatedAt:new Date().toISOString()})
}
function clientResourceAccess_(d){const c=requireClientSession_(d.clientSessionToken,d.phone),p=baFindPurchaseById_(d.purchaseId);if(!p)throw new Error("Purchase not found.");const phone=normalizePhone_(c.clientPhone||d.phone||""),email=String(c.clientEmail||c.email||"").trim().toLowerCase();if(!((email&&p.customerEmail===email)||(phone&&normalizePhone_(p.customerPhone)===phone)))throw new Error("This purchase does not belong to the verified client.");if(!baResourceAccessActive_(p))throw new Error("Resource access is not active.");const r=baFindResource_(p.resourceId);if(!r)throw new Error("Resource not found.");baRecordAccess_(p,"OPEN",String(d.userAgent||""));let url="";try{url=DriveApp.getFileById(r.driveFileId).getUrl()}catch(e){throw new Error("The Google Drive resource is unavailable.")}return json_({ok:true,purchaseId:p.purchaseId,resourceId:r.resourceId,title:r.title,thumbnailUrl:baResourceThumbnailUrl_(r),downloadUrl:url})}

function adminResourceCommerce_(token){requireSuperAdmin_(token);const psh=baPurchaseSheet_(),m=headerMap_(psh),last=psh.getLastRow(),sales=[],summary={USD:{gross:0,paid:0,refunded:0,net:0,count:0}};if(last>1){const vals=psh.getRange(2,1,last-1,psh.getLastColumn()).getValues();for(let i=0;i<vals.length;i++){const p=baPurchaseFromRow_(vals[i],i+2,m);if(!p.purchaseId)continue;const gross=p.amountUSD,ref=p.refundAmountUSD||0;if(p.status==="PAID"||p.status==="REFUNDED"||p.status==="PARTIALLY_REFUNDED"){summary.USD.paid+=gross;summary.USD.count++}if(p.status==="REFUNDED"||ref>0)summary.USD.refunded+=ref;summary.USD.gross+=gross;summary.USD.net=summary.USD.paid-summary.USD.refunded;sales.push({purchaseId:p.purchaseId,resourceId:p.resourceId,resourceTitle:p.resourceTitle,customerName:p.customerName,customerEmail:p.customerEmail,customerPhone:p.customerPhone,amountUSD:gross,currency:p.currency,status:p.status,provider:p.provider,reference:p.reference,createdAt:p.createdAt,paidAt:p.paidAt,refundedAt:p.refundedAt,refundAmountUSD:ref,accessRevokedAt:p.accessRevokedAt})}}
  return json_({ok:true,summary:summary,sales:sales.slice(-500).reverse(),provider:baResourcePaymentProvider_(),generatedAt:new Date().toISOString()})
}
function adminRefundResource_(d){
  requireSuperAdmin_(d.adminToken);const p=baFindPurchaseById_(d.purchaseId);if(!p)throw new Error("Resource purchase not found.");if(["PAID","PARTIALLY_REFUNDED"].indexOf(p.status)<0)throw new Error("Only an active paid resource purchase can be refunded.");const remaining=Math.max(0,p.amountUSD-p.refundAmountUSD);const amount=Number(d.amountUSD||remaining);if(!(amount>0)||amount>remaining)throw new Error("Refund amount must be greater than zero and cannot exceed the purchase amount.");const ref=baPaymentProviderRefund_(p.reference,amount),sh=baPurchaseSheet_();setByHeader_(sh,p.row,"status",amount>=p.amountUSD?"REFUNDED":"PARTIALLY_REFUNDED");setByHeader_(sh,p.row,"refundedAt",new Date());setByHeader_(sh,p.row,"refundAmountUSD",amount);setByHeader_(sh,p.row,"refundReference",String(ref.id||ref.reference||""));if(amount>=p.amountUSD)setByHeader_(sh,p.row,"accessRevokedAt",new Date());auditAdmin_(d.adminToken,"RESOURCE_REFUND",p.purchaseId+" $"+amount.toFixed(2));return json_({ok:true,purchaseId:p.purchaseId,status:amount>=p.amountUSD?"REFUNDED":"PARTIALLY_REFUNDED",refundAmountUSD:amount,refundReference:String(ref.id||ref.reference||"")})
}
function baHandleResourcePaystackWebhook_(tx){const ref=String(tx&&tx.reference||"");if(!ref)return false;const p=baFindPurchaseByReference_(ref);if(!p)return false;try{baVerifyAndRecordResourcePurchase_(ref)}catch(e){console.error("Resource webhook verification failed: "+e)}return true}
function adminResourceAnalytics_(token){
  requireSuperAdmin_(token);
  const resources=baResourceList_(false), resourceMap={};
  resources.forEach(function(r){resourceMap[r.resourceId]={resourceId:r.resourceId,title:r.title,category:r.category||"Uncategorized",published:!!r.published,priceUSD:Number(r.priceUSD||0),salesCount:0,paidRevenueUSD:0,refundedUSD:0,netRevenueUSD:0,accessCount:0,downloadCount:0,lastAccessAt:"",lastDownloadAt:""};});
  const psh=baPurchaseSheet_(),pm=headerMap_(psh),plast=psh.getLastRow();
  if(plast>1){const vals=psh.getRange(2,1,plast-1,psh.getLastColumn()).getValues();for(let i=0;i<vals.length;i++){const p=baPurchaseFromRow_(vals[i],i+2,pm),x=resourceMap[p.resourceId];if(!x)continue;if(p.status==="PAID"||p.status==="REFUNDED"||p.status==="PARTIALLY_REFUNDED"){x.salesCount++;x.paidRevenueUSD+=Number(p.amountUSD||0);x.refundedUSD+=Number(p.refundAmountUSD||0);x.netRevenueUSD=x.paidRevenueUSD-x.refundedUSD;}}}
  const ash=baAccessSheet_(),am=headerMap_(ash),alast=ash.getLastRow();
  if(alast>1){const vals=ash.getRange(2,1,alast-1,ash.getLastColumn()).getValues();for(let i=0;i<vals.length;i++){const row=vals[i],rid=String(row[am.resourceId-1]||""),x=resourceMap[rid];if(!x)continue;x.accessCount+=Number(row[am.accessCount-1]||0);x.downloadCount+=Number(row[am.downloadCount-1]||0);const la=row[am.lastAccessAt-1]||"",ld=row[am.lastDownloadAt-1]||"";if(la&&(!x.lastAccessAt||new Date(la)>new Date(x.lastAccessAt)))x.lastAccessAt=la;if(ld&&(!x.lastDownloadAt||new Date(ld)>new Date(x.lastDownloadAt)))x.lastDownloadAt=ld;}}
  const performance=Object.keys(resourceMap).map(function(k){return resourceMap[k]}).sort(function(a,b){return b.netRevenueUSD-a.netRevenueUSD||b.salesCount-a.salesCount||b.accessCount-a.accessCount||String(a.title).localeCompare(String(b.title))});
  const categories={};performance.forEach(function(x){const key=x.category||"Uncategorized";if(!categories[key])categories[key]={category:key,salesCount:0,paidRevenueUSD:0,refundedUSD:0,netRevenueUSD:0,accessCount:0,downloadCount:0,resourceCount:0};const c=categories[key];c.salesCount+=x.salesCount;c.paidRevenueUSD+=x.paidRevenueUSD;c.refundedUSD+=x.refundedUSD;c.netRevenueUSD+=x.netRevenueUSD;c.accessCount+=x.accessCount;c.downloadCount+=x.downloadCount;c.resourceCount++;});
  const categoryRows=Object.keys(categories).map(function(k){return categories[k]}).sort(function(a,b){return b.netRevenueUSD-a.netRevenueUSD||b.salesCount-a.salesCount||String(a.category).localeCompare(String(b.category))});
  const summary={resources:resources.length,published:resources.filter(function(r){return r.published}).length,salesCount:0,paidRevenueUSD:0,refundedUSD:0,netRevenueUSD:0,accessCount:0,downloadCount:0};performance.forEach(function(x){summary.salesCount+=x.salesCount;summary.paidRevenueUSD+=x.paidRevenueUSD;summary.refundedUSD+=x.refundedUSD;summary.netRevenueUSD+=x.netRevenueUSD;summary.accessCount+=x.accessCount;summary.downloadCount+=x.downloadCount;});
  return json_({ok:true,generatedAt:new Date().toISOString(),provider:baResourcePaymentProvider_(),summary:summary,resources:performance,categories:categoryRows});
}

function adminResourceAccessLookup_(token,query){
  requireSuperAdmin_(token);
  const q=String(query||"").trim().toLowerCase();
  if(q.length<2)throw new Error("Enter at least 2 characters to search resource purchases.");
  const sh=baPurchaseSheet_(),m=headerMap_(sh),last=sh.getLastRow(),out=[];
  if(last>1){const vals=sh.getRange(2,1,last-1,sh.getLastColumn()).getValues();for(let i=vals.length-1;i>=0&&out.length<200;i--){const p=baPurchaseFromRow_(vals[i],i+2,m),hay=[p.purchaseId,p.resourceId,p.resourceTitle,p.customerName,p.customerEmail,p.customerPhone,p.reference].join(" ").toLowerCase();if(hay.indexOf(q)<0)continue;const a=baFindAccessByPurchaseId_(p.purchaseId);const am=a?headerMap_(baAccessSheet_()):null;out.push({purchaseId:p.purchaseId,resourceId:p.resourceId,resourceTitle:p.resourceTitle,customerName:p.customerName,customerEmail:p.customerEmail,customerPhone:p.customerPhone,amountUSD:p.amountUSD,currency:p.currency,status:p.status,reference:p.reference,paidAt:p.paidAt,refundedAt:p.refundedAt,accessStatus:a&&am?(function(){const st=String(a.values[am.accessStatus-1]||"ACTIVE").toUpperCase(),ex=am.expiresAt?a.values[am.expiresAt-1]:"";if(st==="ACTIVE"&&ex&&new Date(ex).getTime()<=Date.now())return "EXPIRED";return st})():"ACTIVE",expiresAt:a&&am&&am.expiresAt?a.values[am.expiresAt-1]||"":"",accessCount:a&&am?Number(a.values[am.accessCount-1]||0):0,downloadCount:a&&am?Number(a.values[am.downloadCount-1]||0):0,lastAccessAt:a&&am?a.values[am.lastAccessAt-1]||"":"",lastDownloadAt:a&&am?a.values[am.lastDownloadAt-1]||"":""});}}
  return json_({ok:true,query:q,results:out,generatedAt:new Date().toISOString()});
}
function adminSetResourceAccess_(d){
  requireSuperAdmin_(d.adminToken);
  const p=baFindPurchaseById_(d.purchaseId);if(!p)throw new Error("Resource purchase not found.");
  const status=String(d.accessStatus||"").toUpperCase();if(["ACTIVE","REVOKED"].indexOf(status)<0)throw new Error("Access status must be ACTIVE or REVOKED.");
  if(p.status!=="PAID"||p.accessRevokedAt)throw new Error("Only an active paid purchase can have its access changed.");
  const sh=baAccessSheet_(),a=baEnsureAccess_(p),now=new Date();setByHeader_(sh,a.row,"accessStatus",status);
  if(status==="ACTIVE"){if(!getByHeader_(sh,a.row,"firstGrantedAt"))setByHeader_(sh,a.row,"firstGrantedAt",now);setByHeader_(sh,a.row,"expiresAt",baAccessExpiryForPurchase_(p,now));}else{setByHeader_(sh,a.row,"expiresAt",getByHeader_(sh,a.row,"expiresAt")||"");}baResourceInvalidateIndexes_();
  auditAdmin_(d.adminToken,status==="ACTIVE"?"RESOURCE_ACCESS_RESTORED":"RESOURCE_ACCESS_REVOKED",p.purchaseId);
  return json_({ok:true,purchaseId:p.purchaseId,resourceId:p.resourceId,accessStatus:status,changedAt:now.toISOString()});
}

function adminResourceReconciliation_(token){requireSuperAdmin_(token);const psh=baPurchaseSheet_(),m=headerMap_(psh),last=psh.getLastRow(),issues=[],totals={paid:0,refunded:0,net:0,purchases:0};if(last>1){const vals=psh.getRange(2,1,last-1,psh.getLastColumn()).getValues();for(let i=0;i<vals.length;i++){const p=baPurchaseFromRow_(vals[i],i+2,m);if(!p.purchaseId)continue;totals.purchases++;if(p.status==="PAID"||p.status==="REFUNDED"||p.status==="PARTIALLY_REFUNDED")totals.paid+=p.amountUSD;totals.refunded+=p.refundAmountUSD||0;const expected=baFindResource_(p.resourceId);if(!expected)issues.push({purchaseId:p.purchaseId,type:"MISSING_RESOURCE",detail:p.resourceId});if(p.currency!=="USD")issues.push({purchaseId:p.purchaseId,type:"CURRENCY_MISMATCH",detail:p.currency});if(p.status==="REFUNDED"&&!(p.refundAmountUSD>=p.amountUSD))issues.push({purchaseId:p.purchaseId,type:"REFUND_AMOUNT_MISMATCH",detail:p.refundAmountUSD+" / "+p.amountUSD})}}totals.net=totals.paid-totals.refunded;return json_({ok:true,totals:totals,issues:issues.slice(0,200),provider:baResourcePaymentProvider_(),generatedAt:new Date().toISOString()})}
