/* BrightAce V42 — request security gateway. Authentication/ownership checks remain in the existing business functions. */
const BA_ALLOWED_ACTIONS_=new Set([
  'startChat','returningClientSendVerification','returningClientVerify','verifyChat','resendVerification','sendVerification','notifyAdmin','sendContactEmail','sendMessage','deliverMessage','initializePayment','adminLogin','adminSessionProfile','adminListConversations','adminGetConversation','adminSendMessage','adminDeliverMessage','adminListTutors','adminAddTutor','adminSetTutorStatus','adminListClients','adminAddClient','adminSetClientStatus','adminListBlockedWhatsApp','adminSetWhatsAppBlock','adminGetRequestIntakeStatus','adminSetRequestIntake','adminAssignWork','adminClaimWork','adminListAdmins','adminAddAdmin','adminUpdateAdmin','adminSetAdminStatus','adminListActivity','adminListPayments','adminDeletePaymentNotification','adminCreatePaymentRequest','deliverPaymentRequest','adminMarkWorkCompleted','adminRejectWork','adminRestoreWork','adminListWorkAssignments','adminListWorkHistory','adminSendTutorMessage','adminGetTutorMessages','adminTutorPortalPreview','adminListTutorBalances','adminListTutorEarningsDetails','adminMarkTutorBalancePaid','adminRecordTutorPayment','submitRefundRequest','adminListRefundRequests','adminReviewRefundRequest','clientDashboard','clientSubmitFeedback','clientSendComment','tutorSendVerification','tutorVerifyLogin','tutorSessionProfile','tutorUploadProfile','tutorRemoveProfile','tutorDashboard','tutorUpdateWorkStatus','tutorSubmitWork','tutorAddWorkComment','tutorSendAdminMessage','tutorGetAdminMessages','tutorGetWallet','tutorSaveWallet','adminListTutorWallets','tutorRequestWithdrawal','tutorListWithdrawals','adminListTutorWithdrawals','adminPayTutorWithdrawal','adminCheckTutorAvailability','adminGetTutorAvailability','adminCreateSchedule','adminListSchedules','adminUpdateSchedule','adminListQuality','clientDashboardBootstrap','clientTouchSession','clientEndSession','clientGetRequest','adminDeleteWorkHistory','tutorAcceptWork','tutorDeclineWork','adminQaWork','registerStatement','tutorSaveAvailability','resourceInitializePayment','resourceDownload','clientResourceLibrary','clientResourceCatalog','clientResourceAccess','adminListResources','adminSaveResource','adminDeleteResource','adminResourceCommerce','adminResourceAnalytics','adminResourceAccessLookup','adminSetResourceAccess','adminResourceReconciliation','adminRefundResource','adminCreateRecoverySnapshot','adminFinancialIntegrity','adminObservability','adminRecoveryManifest','adminProductionQa','adminProductionReadiness'
]);
const BA_ALLOWED_GET_ACTIONS_=new Set(['health','version','messages','paymentRequest','verifyPayment','clientStatement','tutorStatement','adminStatement','verifyStatement','tutorSessionProfile','tutorDashboard','tutorGetWallet','tutorListWithdrawals','tutorGetAdminMessages','adminSessionProfile','adminListConversations','adminListWorkAssignments','adminListClients','adminListTutors','adminListQuality','adminListActivity','adminListTutorBalances','adminListTutorWallets','adminListTutorWithdrawals','adminListWorkHistory','adminHistory','adminWorkHistory','adminListHistory','history','adminListTutorEarningsDetails','resources','resourceVerifyPayment','resourceDownload','clientResourceLibrary','clientResourceCatalog','clientResourceAccess','adminResourceCommerce','adminResourceAnalytics','adminResourceAccessLookup','adminSetResourceAccess','adminResourceReconciliation','adminListResources','adminFinancialIntegrity','adminObservability','adminRecoveryManifest','adminProductionQa','adminProductionReadiness']);
function baSecurityGatePost_(body){
  if(body&&body.object==='whatsapp_business_account')return true;
  if(body&&body.event&&body.data){baRateLimit_(body,'paystackWebhook');return true;}
  const action=String(body&&body.action||'');if(!BA_ALLOWED_ACTIONS_.has(action)){baSecurityEvent_('UNKNOWN_ACTION',action);throw new Error('Unknown BrightAce action.');}
  baValidateActionInput_(body);baRateLimit_(body,action);return true;
}
function baSecurityGateGet_(params){
  const action=String(params&&params.action||'health');if(!BA_ALLOWED_GET_ACTIONS_.has(action)){baSecurityEvent_('UNKNOWN_GET_ACTION',action);throw new Error('Unknown BrightAce GET action.');}
  if(action!=='health')baRateLimit_(params,action);return true;
}
